document.addEventListener('DOMContentLoaded',function(){
var selected={rental:50000,guest:0,menu:0,waiter:0,shooting:0,extras:0};
var labels={rental:'2 Saatlik Plan',guest:'0 - 50 Kişi',menu:'Menü Eklenmedi',waiter:'Garson Eklenmedi',shooting:'Çekim Eklenmedi'};
function tl(n){return new Intl.NumberFormat('tr-TR').format(n)+' TL'}
function total(){var t=0;Object.keys(selected).forEach(function(k){t+=selected[k]});return t}
function write(){var t=tl(total());['summaryTotal','formTotal','mobileTotal'].forEach(function(id){var el=document.getElementById(id);if(el)el.textContent=t});var html='';[['Kiralama',selected.rental],['Konuk',selected.guest],['Menü',selected.menu],['Garson',selected.waiter],['Çekim',selected.shooting],['Ek Hizmetler',selected.extras]].forEach(function(r){html+='<div class="summary-row"><span>'+r[0]+'</span><strong>'+(r[1]?tl(r[1]):(r[0]=='Konuk'?'Dahil':r[0]=='Ek Hizmetler'?'Seçilmedi':'Eklenmedi'))+'</strong></div>'});['summaryRows','formRows'].forEach(function(id){var el=document.getElementById(id);if(el)el.innerHTML=html})}
function open(){var intro=document.getElementById('intro');if(intro){intro.classList.add('is-hidden');setTimeout(function(){intro.style.display='none'},500)}document.body.classList.add('site-open');document.body.classList.remove('no-scroll')}
function screen(name){document.querySelectorAll('.screen').forEach(function(s){s.classList.remove('active')});document.body.classList.remove('form-open','done-open');var el=document.getElementById(name+'Screen');if(el)el.classList.add('active');if(name==='form')document.body.classList.add('form-open');if(name==='done')document.body.classList.add('done-open');scrollTo(0,0)}
document.body.classList.add('no-scroll');
document.getElementById('startBtn').addEventListener('click',open);
document.getElementById('continueBtn').addEventListener('click',function(){screen('form')});
document.getElementById('mobileContinueBtn').addEventListener('click',function(){screen('form')});
document.getElementById('backBtn').addEventListener('click',function(){screen('planner')});
document.getElementById('resetBtn').addEventListener('click',function(){location.reload()});
document.getElementById('planner').addEventListener('click',function(e){var b=e.target.closest('.choice');if(!b)return;var g=b.dataset.group;var p=Number(b.dataset.price||0);if(b.dataset.multiple==='true'){b.classList.toggle('selected');selected.extras+=b.classList.contains('selected')?p:-p}else{document.querySelectorAll('.choice[data-group="'+g+'"]').forEach(function(x){x.classList.remove('selected')});b.classList.add('selected');selected[g]=p;labels[g]=b.dataset.label}write()});
document.getElementById('customerForm').addEventListener('submit',function(e){e.preventDefault();var f=new FormData(e.currentTarget);var ex=Array.from(document.querySelectorAll('.choice[data-multiple="true"].selected')).map(function(x){return x.dataset.label}).join(', ')||'Yok';document.getElementById('receipt').innerHTML='<div class="receipt-card"><h3>Müşteri Bilgileri</h3><div class="receipt-line"><span>Ad Soyad</span><strong>'+(f.get('name')||'-')+'</strong></div><div class="receipt-line"><span>Telefon</span><strong>'+(f.get('phone')||'-')+'</strong></div><div class="receipt-line"><span>E-posta</span><strong>'+(f.get('email')||'-')+'</strong></div><div class="receipt-line"><span>Davet Tarihi</span><strong>'+(f.get('date')||'-')+'</strong></div></div><div class="receipt-card"><h3>Seçimler</h3><div class="receipt-line"><span>Kiralama</span><strong>'+labels.rental+'</strong></div><div class="receipt-line"><span>Konuk</span><strong>'+labels.guest+'</strong></div><div class="receipt-line"><span>Menü</span><strong>'+labels.menu+'</strong></div><div class="receipt-line"><span>Garson</span><strong>'+labels.waiter+'</strong></div><div class="receipt-line"><span>Çekim</span><strong>'+labels.shooting+'</strong></div><div class="receipt-line"><span>Ek Hizmetler</span><strong>'+ex+'</strong></div><div class="receipt-line"><span>Toplam</span><strong>'+tl(total())+'</strong></div></div>';screen('done')});
document.getElementById('copyBtn').addEventListener('click',function(){alert('Sipariş özeti hazır')});
document.getElementById('mailBtn').addEventListener('click',function(){alert('Mail için özet ekrandan kontrol edilebilir')});
document.getElementById('printBtn').addEventListener('click',function(){print()});
write();
});